### ISSUE TITLE
Could not write standard input into: Gradle Worker 1

### ISSUE THREAD

**Issue by wcomnisky** [mkuthan/design-nestedset#1]
Running <code>gradle check</code> in the project I'm getting the following error.

I'm using Java 1.8.0_66-b18 64bits with Windows 8.0.

Partial log using <code>gradle check --stacktrace --debug</code>:

<pre>
12:00:35.706 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
12:00:35.715 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: Gradle Worker 1.
12:00:35.730 [INFO] [org.gradle.process.internal.ProcessParentingInitializer] An attempt to initialize for well behaving parent process finished.
12:00:35.761 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
12:00:35.775 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'Gradle Worker 1'
12:00:35.775 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
12:00:36.004 [ERROR] [system.err] java.lang.reflect.InvocationTargetException
12:00:36.005 [QUIET] [system.out] FATAL ERROR in native method: processing of -javaagent failed

12:00:36.014 [ERROR] [org.gradle.process.internal.streams.ExecOutputHandleRunner] Could not write standard input into: Gradle Worker 1.
java.io.IOException: O pipe estß sendo fechado
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:50)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
12:00:36.013 [ERROR] [system.err]
12:00:36.041 [ERROR] [system.err]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:00:36.047 [ERROR] [system.err]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:00:36.055 [ERROR] [system.err]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:00:36.060 [ERROR] [system.err]       at java.lang.reflect.Method.invoke(Method.java:497)
12:00:36.073 [ERROR] [system.err]       at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
12:00:36.079 [ERROR] [system.err]       at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
12:00:36.088 [ERROR] [system.err] Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
12:00:36.093 [ERROR] [system.err]       at org.jacoco.agent.rt.internal_5d10cad.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
12:00:36.102 [ERROR] [system.err]       at org.jacoco.agent.rt.internal_5d10cad.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:99)
12:00:36.107 [ERROR] [system.err]       at org.jacoco.agent.rt.internal_5d10cad.PreMain.createRuntime(PreMain.java:51)
12:00:36.122 [ERROR] [system.err]       at org.jacoco.agent.rt.internal_5d10cad.PreMain.premain(PreMain.java:43)
12:00:36.127 [ERROR] [system.err]       ... 6 more
12:00:36.135 [ERROR] [system.err] Caused by: java.lang.NoSuchFieldException: $jacocoAccess
12:00:36.140 [ERROR] [system.err]       at java.lang.Class.getField(Class.java:1703)
12:00:36.145 [ERROR] [system.err]       at org.jacoco.agent.rt.internal_5d10cad.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:136)
12:00:36.155 [ERROR] [system.err]       ... 9 more
12:00:36.159 [ERROR] [system.err] Exception in thread "main"
12:00:36.171 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
12:00:36.183 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'Gradle Worker 1' finished with exit value 1 (state: FAILED)
12:00:36.195 [DEBUG] [TestEventLogger]
12:00:36.206 [DEBUG] [TestEventLogger] Test Run PASSED
12:00:36.222 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':test'
12:00:36.236 [LIFECYCLE] [org.gradle.TaskExecutionLogger] :test FAILED
12:00:36.245 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :test (Thread[main,5,main]) completed. Took 4.424 secs.
12:00:36.256 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 5.896 secs, idle: 0.124 secs
12:00:36.274 [ERROR] [org.gradle.BuildExceptionReporter]
12:00:36.289 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
12:00:36.305 [ERROR] [org.gradle.BuildExceptionReporter]
12:00:36.319 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
12:00:36.326 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':test'.
12:00:36.337 [ERROR] [org.gradle.BuildExceptionReporter] > Process 'Gradle Worker 1' finished with non-zero exit value 1
12:00:36.349 [ERROR] [org.gradle.BuildExceptionReporter]
12:00:36.359 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
12:00:36.375 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test'.
12:00:36.386 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
12:00:36.395 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
12:00:36.406 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
12:00:36.419 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
12:00:36.426 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
12:00:36.435 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
12:00:36.441 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
12:00:36.453 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
12:00:36.463 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
12:00:36.473 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:286)
12:00:36.479 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
12:00:36.486 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
12:00:36.493 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
12:00:36.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$1.run(DefaultTaskPlanExecutor.java:33)
12:00:36.512 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Factories$1.create(Factories.java:22)
12:00:36.522 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheAccess.longRunningOperation(DefaultCacheAccess.java:198)
12:00:36.528 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheAccess.longRunningOperation(DefaultCacheAccess.java:266)
12:00:36.536 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.longRunningOperation(DefaultPersistentDirectoryStore.java:135)
12:00:36.541 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.changedetection.state.DefaultTaskArtifactStateCacheAccess.longRunningOperation(DefaultTaskArtifactStateCacheAccess.java:93)
12:00:36.553 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:31)
12:00:36.612 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:86)
12:00:36.621 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
12:00:36.632 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
12:00:36.642 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
12:00:36.647 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
12:00:36.654 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
12:00:36.659 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
12:00:36.667 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:54)
12:00:36.674 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:166)
12:00:36.680 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
12:00:36.687 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
12:00:36.692 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:64)
12:00:36.702 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
12:00:36.709 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
12:00:36.720 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:35)
12:00:36.726 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
12:00:36.732 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
12:00:36.739 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
12:00:36.744 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
12:00:36.752 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
12:00:36.758 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
12:00:36.767 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
12:00:36.773 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
12:00:36.786 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
12:00:36.793 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:46)
12:00:36.802 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
12:00:36.807 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.main(Main.java:37)
12:00:36.818 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
12:00:36.824 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
12:00:36.835 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
12:00:36.841 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
12:00:36.850 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
12:00:36.855 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:58)
12:00:36.861 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.process.internal.ExecException: Process 'Gradle Worker 1' finished with non-zero exit value 1
12:00:36.871 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:361)
12:00:36.876 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:89)
12:00:36.883 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:33)
12:00:36.888 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:55)
12:00:36.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
12:00:36.905 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
12:00:36.911 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
12:00:36.919 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
12:00:36.924 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
12:00:36.934 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.proxy.$Proxy39.executionFinished(Unknown Source)
12:00:36.939 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:209)
12:00:36.951 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:306)
12:00:36.958 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:105)
12:00:36.968 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:85)
12:00:36.973 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:66)
12:00:36.985 [ERROR] [org.gradle.BuildExceptionReporter]
12:00:36.990 [LIFECYCLE] [org.gradle.BuildResultLogger]
12:00:37.000 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
12:00:37.007 [LIFECYCLE] [org.gradle.BuildResultLogger]
12:00:37.019 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 15.745 secs
</pre>

**Comment by wcomnisky** [comment]
Fixed with the PR https://github.com/mkuthan/design-nestedset/pull/2
